version: "3.6"
services:
  web:
    build: web
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - flask_network
  proxy:
    build: proxy
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - flask_network
  db:
    image: postgres:10
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - flask_network
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  flask_network:

volumes:
  postgres_data: